#!/bin/bash
set -eu

yarn lint
yarn type-check

.scripts/list-todos NO-TICKET

BRANCH=${BRANCH:-$(git rev-parse --abbrev-ref HEAD)}
if [[ $BRANCH =~ (feature|hotfix)/(([A-Z0-9]+-|#)?[0-9]+) ]]; then
    TICKET="${BASH_REMATCH[2]}"
    .scripts/list-todos "$TICKET"
fi
